apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: piloto
  labels:
    service: backend
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    service: backend