apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: "piloto"
  labels:
    service: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        service: frontend
        api: external
    spec:
      containers:
      - name: frontend
        image: frontend_app
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m