apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: "piloto"
  labels:
    service: frontend
spec:
  selector:
    service: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer