apiVersion: v1
kind: Service
metadata:
  namespace: piloto
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
  - name: "5000"
    port: 80
    targetPort: 5000
  selector:
    service: reverseproxy
  type: LoadBalancer