"""empty message

Revision ID: 311493088bc4
Revises: 057fc1d04da6
Create Date: 2021-12-09 17:03:33.111612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311493088bc4'
down_revision = '057fc1d04da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codigos', sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codigos', 'fecha_registro')
    # ### end Alembic commands ###
