"""empty message

Revision ID: cb3f9c6fc422
Revises: 
Create Date: 2021-12-09 12:37:05.351376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3f9c6fc422'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('detalle', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('foto', sa.String(), nullable=False),
    sa.Column('stock_sin_despachar', sa.Integer(), nullable=False),
    sa.Column('stock_real', sa.Integer(), nullable=False),
    sa.Column('puntos', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.Column('contraseña', sa.String(), nullable=True),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('cedula', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('numero_semana', sa.String(), nullable=False),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('año', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canjes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_semana', sa.String(), nullable=False),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('año', sa.String(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('nombre_cliente', sa.String(), nullable=True),
    sa.Column('total_puntos', sa.Float(), nullable=True),
    sa.Column('cantidad_total', sa.Float(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codigos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('canjeado', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_canje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canje_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('numero_semana', sa.String(), nullable=False),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('año', sa.String(), nullable=False),
    sa.Column('puntos', sa.Float(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('codigo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['canje_id'], ['canjes.id'], ),
    sa.ForeignKeyConstraint(['codigo_id'], ['codigos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_canje')
    op.drop_table('codigos')
    op.drop_table('canjes')
    op.drop_table('usuarios')
    op.drop_table('productos')
    # ### end Alembic commands ###
